### ISSUE TITLE
users not able to login

### ISSUE THREAD

**Issue by novski** [cdubz/babybuddy#49]
After adding a user in the admin panel i can not login with the credentials.
I don't get a error or message.  A Pageload hapens and the login page apears again. 
Admin login works.
How can i debug that?

**Comment by cdubz** [comment]
It sounds like you created the user in the "Backend Admin" (http://babybuddy.local/admin/) without any permissions. I'll see about adding a notification for lack of permissions (instead of just redirecting back to login).

If you create the user from the custom "Users" page (http://babybuddy.local/users/), the permissions are set up automatically. Give that a try and let me know if it works.

**Comment by novski** [comment]
Yes that works. Didn't see the menu in the frontend and because of my previous knowledge about django i thaught it must be in the backend... Sorry for that.
