### ISSUE TITLE
Feature Reqest: Feeding; both Breasts

### ISSUE THREAD

**Issue by novski** [cdubz/babybuddy#52]
Would like to see a third type of Breast feeding: "both Breasts" in the dropdown of "Method".

**Comment by cdubz** [comment]
The reason we included this field is because apparently it is best to start a new feeding session on the opposite breast of the last one. This is why we added the "Last Feeding Method" prominently on the dashboard. For this reason I am disinclined to add a "both" option, unless there is some particular reason that information may be useful.

**Comment by novski** [comment]
My litle already takes both in the same session. So it doubles in the statisics. Maybe a automatic comparsion wold be good to check wether the feeding was in the last hour on both breasts, then take the two feedings together as one session?

**Comment by pitah81** [comment]
I second this option, our child also always feeds 50/50 on each breast per feeding so the option to select both breasts would be much easier than having to start 2 feedings for 1 feeding.

**Comment by cdubz** [comment]
I will pick this up. Can't hurt to have the option for those who want it, of course (:

**Comment by cdubz** [comment]
This is committed to `master`. I'm planning to roll a new release soon so I'll close this ticket after that.
