### ISSUE TITLE
Pine64 Docker install fails

### ISSUE THREAD

**Issue by cdubz** [cdubz/babybuddy#59]
Hi I'm having an issue, not directly with manual installation but with Docker on a ARM 64 board, to be more accurate Pine64 with Arch Linux on it.

Seems like, panda is missing, and a couple of gcc to compile --

[iNaT import error.txt](https://github.com/cdubz/babybuddy/files/2753290/iNaT.import.error.txt)

The traceback is huge, let me know if you want it as well.

_Originally posted by @killua99 in https://github.com/cdubz/babybuddy/issues/55#issuecomment-453791242_

**Comment by cdubz** [comment]
@killua99 I'm breaking this out in to it's own issue. I'm not able to recreate that environment so I'm afraid I can't help much here. May as well post the full trackback, though (preferably as an attachment).

**Comment by killua99** [comment]
Hi @cdubz thanks for this excellent app.

I manage to solve it, turns out the docker require extra packages, I will test further on different architectures as well different hosts, like Mac and Windows.

For my ARM64 this is what I did to solve it.

- Clone the repo and checkout to the latest tag
- Fix the docker.env as the README says
- Run `docker-compose up -d`
- Run `docker-compose exec app pip install pandas==0.23.0 --force --no-cache`
- Run `docker-compose exec app python manage.py migrate`

See, the key was install pandas before the migrate, with that I mange to install properly Baby Buddy 👍
