### ISSUE TITLE
FR: Diaper change volume

### ISSUE THREAD

**Issue by TJM** [cdubz/babybuddy#77]
A thought I had was adding an optional volume for diaper changes. You could start with something easy like "barely wet, wet, really wet, niagara falls" or If you are tracking I/O, just offer a field for ml (grams). A simple scale could handle that, I think. It might even be useful as a way to determine if the "premium" diapers are worth the extra cost? Maybe thats an entirely separate app too :)

**Comment by r0n0c** [comment]
I had a similar thought. I was less concerned with the wetness, and more
concerned with the BM, was it a real deal big one, or a shart? Both are
useful information IE has baby been totally plugged for days or are things
moving just not a lot.

What we did was only assign color to real deal dirty diapers, sharts just
get marked, no color.  I did a similar thing with bottle volumes, if the
baby finished the bottle empty the volume ends in 0 (we measure in ml)
90/100/60. If they couldn't quit finish off the bottle it ends in any other
digit. It gave me this info at a glance without any modification to the
app.

That all said I am not sure how to implement a grading to the wetness. Are
you already weighing diapers? When we had to do that in the NICU we had to
have a preapplied diaper weight and then the after used weight since
diapers (even the same brand/size) often varied so much in weight that it
could cancel out any urine being measured. Meaning, its a lot of work. But
if you need it, use the Notes. It is super flexible.

**Comment by TJM** [comment]
We are not *currently* weighing each diaper, but have in the past, and likely will again. Honestly, for as often as we need to do it, the notes would probably work. However, if we were able to record the data as a separate "column" (field?), maths could be done against them easier. 

That is some interesting information on the difference in "tare" weight of dry diapers. We just assumed as long as it was the same size/brand/kind, it would be close enough. Mind you, at size 3/4/5 the quantity of urine vs the mass of the dry diaper is quite different than size P.

Thanks!

**Comment by cdubz** [comment]
I think adding this as a simple generic "amount" field on the Diaper Change model may be acceptable. From a quick search it seems that the general approach is to have a dedicated scale that you zero with the weight of each new diaper and then weigh again (from the adjusted zero) the soiled diaper to get the amount by weight.

**Comment by cdubz** [comment]
This has been added as a generic "amount" field. I didn't think "volume" or "weight" quite fit, but I also don't love "amount". Suggestions for improvement on the terminology or functionality are welcomed.
