### ISSUE TITLE
Allow AM/PM instead of military time

### ISSUE THREAD

**Issue by LostSoulfly** [cdubz/babybuddy#93]
This one is a big roadblock for my wife, and always takes me a few extra seconds to figure out the correct military time. Allowing a 12-hour clock with AM/PM would be a boon.

Thanks for developing this, it's been a big help. I'm on week 7, just started using it a few days ago!

**Comment by cdubz** [comment]
Yeah the app is inconsistent on this -- timers, graphs, dashboard cards, and _some_ list views (notes and temperature) user 12-hour time and the other list views (including timers list) user 24-hour time. I'll clean this up and probably add a configuration option for it.

**Comment by cdubz** [comment]
1a31a27 removes existing hardcoded formats so if you are on `master` you can get that change now. I want to make this per-user configurable though so that will come with a later release.

**Comment by cdubz** [comment]
Didn't end up with a user setting in the end, but datetime fields should now all be localized!

**Comment by JeanFred** [comment]
Hi! I’m having the reverse problem: I would like to not use AM/PM but 24H format. I’m using the app in English.

My first thought was `DATETIME_INPUT_FORMATS`, but that is about the input format, not display format. I then thought of setting [DATE_FORMAT](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-DATE_FORMAT) but it seems that it will get overridden anyhow because `USE_L10N` is enabled? (that, and I would presumably need to set `DATETIME_FORMAT`, `TIME_FORMAT` and `SHORT_DATE_FORMAT`)?

Digging further, it appears that `USE_L10N` is conditioned by `LANGUAGE_CODE` ; however that is hardcoded to 'en' (presumably aliased somewhere by Django to `en-us`?) in `babybuddy/babybuddy/settings/base.py`  so I guess it would not be taken into account either?).

Am I missing something?
